version: '3.8'
services:
  web:
    build: .
    image: trilive-backend
    ports:
      - "8000:8000"
    environment:
      - TRIMET_API_KEY: ${TRIMET_API_KEY}
      - DATABASE_URL: ${DATABASE_URL}
      - REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      -pgdata:/var/lib/postgres/data

  redis:
    image: redis:7
